Add string casting to the cls.name
The original line: 
self.class_components = self.cls.name.strip('L').strip(';').split('/')
give the following error during the open phase of several apk files:
TypeError: a bytes-like object is required, not 'str'
The problem can be easily solved casting explicitly the cls.name to string before manipulate it.