Fix #1031 & #764 - androguard sign .fingerprint removed
This commit replaces the outdated:
    asn1crypto.keys.PublicKeyInfo().fingerprint` call

With the new:
    oscrypto.asymmetric.PublicKey().fingerprint` call

ValueError/ve is properly excepted and when printed, it shows "Only DSA keys are generated using a hash algorithm, this key is RSA" for RSA signed apk's.

This commit satisfies the:
    asn1crypto._errors.APIException: asn1crypto.keys.PublicKeyInfo().fingerprint has been removed, please use oscrypto.asymmetric.PublicKey().fingerprint instead`
while still keeping the original behavior.